spring.application.name=SPRINGBOOT_BASE


spring.main.banner-mode=console

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

openapi.service.api-docs= api-service
openapi.service.serverUrl= http://localhost:8080
openapi.service.title= API Document
openapi.service.version= 1.0.0
openapi.service.description= Mo ta API Moi Truong Test
