spring.application.name=SPRINGBOOT_BASE

# MySQL config
spring.datasource.url=jdbc:mysql://localhost:3306/base_tayjava?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=Ch@/12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.main.banner-mode=console

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=


open.api.title=API SERVICE DOCUMENT
open.api.version=v1.0.0
open.api.description=API DOCUMENT
open.api.serverUrl=http://localhost:8080
openapi.service.api-docs=